# -*- coding: utf-8 -*-
"""UI layout and communication-control mixin for the UWB location tool.

This module owns all code-created layout on top of the Qt Designer base UI.
It also owns adaptive sizing: dimensions that look fixed are derived from the
current screen so the same composition works on laptop displays, 1080p
monitors, and high-DPI large screens.
"""
import ipaddress
import socket
from threading import Thread

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import Qt
from PyQt5.QtGui import QBrush, QColor
from PyQt5.QtWidgets import QAbstractItemView, QMessageBox

import globalvar
from twr_comm import list_ports, serial


gAnthor_Node_Configure = globalvar.get_anthor()


class UILayoutMixin:
    """Window layout, adaptive screen sizing, status bar, and connection UI."""

    DESIGN_WINDOW_WIDTH = 956
    DESIGN_WINDOW_HEIGHT = 1935
    MIN_WINDOW_WIDTH = 820
    MIN_WINDOW_HEIGHT = 720

    @staticmethod
    def available_screen_geometry():
        """Return primary-screen available geometry with a safe fallback."""
        screen = QtGui.QGuiApplication.primaryScreen()
        if screen is None:
            return QtCore.QRect(0, 0, 1366, 768)
        return screen.availableGeometry()

    def adaptive_px(self, value, minimum=None, maximum=None):
        """Scale a design-time pixel value by the active layout scale."""
        scale = getattr(self, "ui_scale", 1.0)
        scaled = int(round(value * scale))
        if minimum is not None:
            scaled = max(int(minimum), scaled)
        if maximum is not None:
            scaled = min(int(maximum), scaled)
        return scaled

    def configure_adaptive_window(self):
        """Choose startup/minimum window sizes from the current display."""
        available = self.available_screen_geometry()
        target_width = min(self.DESIGN_WINDOW_WIDTH, max(self.MIN_WINDOW_WIDTH, int(available.width() * 0.92)))
        target_height = min(self.DESIGN_WINDOW_HEIGHT, max(self.MIN_WINDOW_HEIGHT, int(available.height() * 0.90)))
        target_width = min(target_width, max(640, available.width() - 24))
        target_height = min(target_height, max(520, available.height() - 48))
        self.target_window_width = target_width
        self.target_window_height = target_height

        self.ui_scale = max(
            0.76,
            min(
                1.0,
                target_width / float(self.DESIGN_WINDOW_WIDTH),
                target_height / float(self.DESIGN_WINDOW_HEIGHT),
            ),
        )
        min_width = min(self.MIN_WINDOW_WIDTH, max(640, available.width() - 24))
        min_height = min(self.MIN_WINDOW_HEIGHT, max(520, available.height() - 48))
        self.resize(target_width, target_height)
        self.setMinimumSize(min_width, min_height)

    def apply_localized_texts(self):
        """Apply visible labels to widgets generated by ``mainwindow.py``."""
        self.setWindowTitle("蓝点UWB-TWR 上位机V1.0")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), "定位")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), "调试")
        self.btn_start.setText("开始")
        self.btn_clear.setText("清空")
        self.groupBox.setTitle("TCP")
        self.label.setText("本机IP:")
        self.label_2.setText("端口Port:")
        self.pushButton.setText("OPEN")
        self.label_port_state.setText("")
        self.groupBox_3.setTitle("定位结果")
        self.groupBox_4.setTitle("基站配置")

        tag_headers = ["地址", "x", "y", "z"]
        for column, text in enumerate(tag_headers):
            item = self.table_tag.horizontalHeaderItem(column)
            if item is not None:
                item.setText(text)

        anthor_headers = ["使能", "地址", "x", "y", "z"]
        for column, text in enumerate(anthor_headers):
            item = self.table_anthor.horizontalHeaderItem(column)
            if item is not None:
                item.setText(text)

    def configure_window_layout(self):
        """Build the full window layout and adaptive control sizes."""
        self.configure_adaptive_window()

        base_font = QtGui.QFont("Microsoft YaHei UI", self.adaptive_px(10, 9))
        base_font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        title_font = QtGui.QFont("Microsoft YaHei UI", self.adaptive_px(11, 10))
        title_font.setBold(True)
        button_font = QtGui.QFont("Microsoft YaHei UI", self.adaptive_px(10, 9))
        button_font.setBold(True)
        status_font = QtGui.QFont("Microsoft YaHei UI", self.adaptive_px(11, 10, 13))
        status_font.setBold(True)

        for widget in self.findChildren(QtWidgets.QWidget):
            widget.setFont(base_font)
        for group in (self.groupBox, self.groupBox_2, self.groupBox_3, self.groupBox_4):
            group.setFont(title_font)

        main_layout = QtWidgets.QVBoxLayout(self.centralWidget)
        main_layout.setContentsMargins(
            self.adaptive_px(14, 10),
            self.adaptive_px(10, 8),
            self.adaptive_px(14, 10),
            self.adaptive_px(14, 10),
        )
        main_layout.setSpacing(self.adaptive_px(10, 8))

        top_panel = QtWidgets.QWidget(self.centralWidget)
        self.top_config_panel = top_panel
        top_layout = QtWidgets.QHBoxLayout(top_panel)
        top_layout.setContentsMargins(0, 0, 0, 0)
        top_layout.setSpacing(self.adaptive_px(14, 10))
        side_layout = QtWidgets.QVBoxLayout()
        side_layout.setSpacing(self.adaptive_px(6, 4))

        top_panel.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        top_panel_min_height = self.adaptive_px(216, 196)
        top_panel.setMinimumHeight(top_panel_min_height)
        top_panel.setMaximumHeight(top_panel_min_height)

        self.groupBox_4.setMinimumSize(self.adaptive_px(340, 300), self.adaptive_px(188, 170))
        self.groupBox_3.setMinimumSize(self.adaptive_px(280, 240), self.adaptive_px(188, 170))
        self.groupBox.setTitle("通信")
        self.groupBox.setMinimumSize(self.adaptive_px(340, 300), self.adaptive_px(188, 170))
        for top_group in (self.groupBox_4, self.groupBox_3, self.groupBox):
            top_group.setMaximumHeight(top_panel_min_height)
        self.groupBox_2.setObjectName("HistoryPanel")
        self.groupBox_2.setMinimumSize(self.adaptive_px(260, 230), self.adaptive_px(50, 44))
        self.groupBox_2.setMaximumHeight(self.adaptive_px(56, 50))
        self.groupBox_2.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        self.groupBox_2.hide()

        anchor_layout = QtWidgets.QVBoxLayout(self.groupBox_4)
        anchor_layout.setContentsMargins(10, self.adaptive_px(22, 18), 10, 10)
        anchor_layout.addWidget(self.table_anthor)

        tag_layout = QtWidgets.QVBoxLayout(self.groupBox_3)
        tag_layout.setContentsMargins(10, self.adaptive_px(22, 18), 10, 10)
        tag_layout.addWidget(self.table_tag)

        self.comm_tab_widget = QtWidgets.QTabWidget(self.groupBox)
        self.tcp_tab = QtWidgets.QWidget()
        self.com_tab = QtWidgets.QWidget()
        self.comm_tab_widget.addTab(self.tcp_tab, "TCP")
        self.comm_tab_widget.addTab(self.com_tab, "COM")
        self.comm_tab_widget.setCurrentWidget(self.com_tab)

        comm_layout = QtWidgets.QVBoxLayout(self.groupBox)
        comm_layout.setContentsMargins(12, self.adaptive_px(24, 18), 12, 12)
        comm_layout.addWidget(self.comm_tab_widget)

        tcp_layout = QtWidgets.QGridLayout(self.tcp_tab)
        tcp_layout.setContentsMargins(12, self.adaptive_px(16, 12), 12, 12)
        tcp_layout.setHorizontalSpacing(self.adaptive_px(10, 8))
        tcp_layout.setVerticalSpacing(self.adaptive_px(10, 8))
        tcp_layout.addWidget(self.label, 0, 0)
        tcp_layout.addWidget(self.label_ip, 0, 1, 1, 2)
        tcp_layout.addWidget(self.label_2, 1, 0)
        tcp_port_row = QtWidgets.QHBoxLayout()
        tcp_port_row.setContentsMargins(0, 0, 0, 0)
        tcp_port_row.setSpacing(self.adaptive_px(8, 6))
        self.lineEdit_Port.setFixedSize(self.adaptive_px(82, 74), self.adaptive_px(34, 30))
        self.pushButton.setFixedSize(self.adaptive_px(84, 78), self.adaptive_px(34, 30))
        tcp_port_row.addWidget(self.lineEdit_Port)
        tcp_port_row.addSpacing(self.adaptive_px(6, 4))
        tcp_port_row.addWidget(self.pushButton)
        tcp_layout.addLayout(tcp_port_row, 1, 1, 1, 2)
        tcp_layout.addWidget(self.label_port_state, 2, 0, 1, 3)
        tcp_layout.setColumnStretch(0, 0)
        tcp_layout.setColumnStretch(1, 0)
        tcp_layout.setColumnStretch(2, 1)
        self.label_port_state.setWordWrap(True)
        self.label_port_state.setAlignment(Qt.AlignCenter)
        self.label_port_state.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        self.label_port_state.hide()

        self.com_port_label = QtWidgets.QLabel("串口:")
        self.com_port_combo = QtWidgets.QComboBox()
        self.com_refresh_button = QtWidgets.QPushButton("刷新")
        self.com_baud_label = QtWidgets.QLabel("波特率:")
        self.com_baud_combo = QtWidgets.QComboBox()
        self.com_baud_combo.addItems(["115200", "921600", "460800", "230400", "57600", "38400", "19200", "9600"])
        self.com_open_button = QtWidgets.QPushButton("OPEN")
        self.com_status_label = QtWidgets.QLabel("")
        self.com_status_label.setStyleSheet("color: #B42318; font-weight: 700;")
        self.com_refresh_button.clicked.connect(self.refresh_serial_ports)
        self.com_open_button.clicked.connect(self.do_serial_start)
        serial_combo_width = self.adaptive_px(118, 106)
        self.com_port_combo.setFixedSize(serial_combo_width, self.adaptive_px(34, 30))
        self.com_refresh_button.setFixedSize(self.adaptive_px(84, 78), self.adaptive_px(34, 30))
        com_font = QtGui.QFont(base_font)
        com_font.setPointSize(max(8, base_font.pointSize() - 2))
        for com_widget in (
            self.com_port_label,
            self.com_port_combo,
            self.com_refresh_button,
            self.com_baud_label,
            self.com_baud_combo,
            self.com_open_button,
            self.com_status_label,
        ):
            com_widget.setFont(com_font)
        self.com_port_label.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
        self.com_baud_label.setAlignment(Qt.AlignRight | Qt.AlignVCenter)

        com_layout = QtWidgets.QGridLayout(self.com_tab)
        com_layout.setContentsMargins(12, self.adaptive_px(16, 12), 12, 12)
        com_layout.setHorizontalSpacing(self.adaptive_px(10, 8))
        com_layout.setVerticalSpacing(self.adaptive_px(10, 8))
        com_layout.addWidget(self.com_port_label, 0, 0, Qt.AlignRight | Qt.AlignVCenter)
        com_port_row = QtWidgets.QHBoxLayout()
        com_port_row.setContentsMargins(0, 0, 0, 0)
        com_port_row.setSpacing(self.adaptive_px(8, 6))
        com_port_row.addWidget(self.com_port_combo, 0, Qt.AlignVCenter)
        com_port_row.addSpacing(self.adaptive_px(6, 4))
        com_port_row.addWidget(self.com_refresh_button, 0, Qt.AlignVCenter)
        com_layout.addLayout(com_port_row, 0, 1, 1, 2)
        com_layout.addWidget(self.com_baud_label, 1, 0, Qt.AlignRight | Qt.AlignVCenter)
        com_baud_row = QtWidgets.QHBoxLayout()
        com_baud_row.setContentsMargins(0, 0, 0, 0)
        com_baud_row.setSpacing(self.adaptive_px(8, 6))
        self.com_baud_combo.setFixedSize(serial_combo_width, self.adaptive_px(34, 30))
        self.com_open_button.setFixedSize(self.adaptive_px(84, 78), self.adaptive_px(34, 30))
        com_baud_row.addWidget(self.com_baud_combo, 0, Qt.AlignVCenter)
        com_baud_row.addSpacing(self.adaptive_px(6, 4))
        com_baud_row.addWidget(self.com_open_button, 0, Qt.AlignVCenter)
        com_layout.addLayout(com_baud_row, 1, 1, 1, 2)
        com_layout.addWidget(self.com_status_label, 2, 0, 1, 3)
        com_layout.setColumnStretch(1, 0)
        com_layout.setColumnStretch(2, 1)
        self.com_status_label.setWordWrap(True)
        self.com_status_label.setAlignment(Qt.AlignCenter)
        self.com_status_label.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        self.com_status_label.hide()

        side_layout.addWidget(self.groupBox)

        top_layout.addWidget(self.groupBox_4, 4)
        top_layout.addWidget(self.groupBox_3, 4)
        top_layout.addLayout(side_layout, 4)
        main_layout.addWidget(top_panel, 0)
        main_layout.addWidget(self.tabWidget, 1)

        locate_layout = QtWidgets.QVBoxLayout(self.tab)
        locate_layout.setContentsMargins(0, 0, 0, 0)
        locate_layout.setSpacing(self.adaptive_px(8, 6))

        zoom_bar = QtWidgets.QHBoxLayout()
        zoom_bar.setContentsMargins(self.adaptive_px(12, 8), self.adaptive_px(10, 8), self.adaptive_px(12, 8), 0)
        self.zoom_text = QtWidgets.QLabel("\u7f29\u653e")
        self.zoom_text.setObjectName("ToolbarText")
        self.zoom_text.setAlignment(Qt.AlignCenter)
        self.zoom_out_button = QtWidgets.QPushButton("-")
        self.zoom_out_button.setObjectName("ZoomButton")
        self.zoom_out_button.setFixedSize(self.adaptive_px(42, 38), self.adaptive_px(32, 30))
        self.zoom_out_button.clicked.connect(self.zoom_out)
        self.zoom_label = QtWidgets.QLabel("100%")
        self.zoom_label.setObjectName("ZoomLabel")
        self.zoom_label.setAlignment(Qt.AlignCenter)
        self.zoom_label.setMinimumWidth(self.adaptive_px(70, 64))
        self.zoom_reset_button = QtWidgets.QPushButton("\u91cd\u7f6e")
        self.zoom_reset_button.setObjectName("ZoomButton")
        self.zoom_reset_button.setFixedSize(self.adaptive_px(78, 72), self.adaptive_px(32, 30))
        self.zoom_reset_button.clicked.connect(self.zoom_reset)
        self.zoom_in_button = QtWidgets.QPushButton("+")
        self.zoom_in_button.setObjectName("ZoomButton")
        self.zoom_in_button.setFixedSize(self.adaptive_px(42, 38), self.adaptive_px(32, 30))
        self.zoom_in_button.clicked.connect(self.zoom_in)
        self.measurement_toggle_button = QtWidgets.QPushButton("\u9690\u85cf\u6d4b\u8ddd")
        self.measurement_toggle_button.setObjectName("ZoomButton")
        self.measurement_toggle_button.setFixedSize(self.adaptive_px(102, 96), self.adaptive_px(32, 30))
        self.measurement_toggle_button.setToolTip("\u663e\u793a\u6216\u9690\u85cf\u6d4b\u8ddd\u5706\u3001\u8ddd\u79bb\u8fde\u7ebf\u548c\u8ddd\u79bb\u6807\u6ce8")
        self.measurement_toggle_button.clicked.connect(self.toggle_measurement_aid)
        separator_size = (self.adaptive_px(1, 1), self.adaptive_px(28, 24))

        def make_toolbar_separator():
            """Create one vertical divider for toolbar control groups."""
            separator = QtWidgets.QFrame()
            separator.setObjectName("ToolbarSeparator")
            separator.setFrameShape(QtWidgets.QFrame.VLine)
            separator.setFrameShadow(QtWidgets.QFrame.Plain)
            separator.setFixedSize(*separator_size)
            return separator

        zoom_bar.addWidget(self.zoom_text)
        zoom_bar.addSpacing(self.adaptive_px(4, 2))
        zoom_bar.addWidget(self.zoom_out_button)
        zoom_bar.addWidget(self.zoom_label)
        zoom_bar.addWidget(self.zoom_reset_button)
        zoom_bar.addWidget(self.zoom_in_button)
        zoom_bar.addSpacing(self.adaptive_px(8, 4))
        zoom_bar.addWidget(make_toolbar_separator())
        zoom_bar.addSpacing(self.adaptive_px(8, 4))
        zoom_bar.addWidget(self.measurement_toggle_button)
        zoom_bar.addSpacing(self.adaptive_px(8, 4))
        zoom_bar.addWidget(make_toolbar_separator())
        zoom_bar.addSpacing(self.adaptive_px(8, 4))
        self.label_3.setText("历史")
        self.label_3.setObjectName("ToolbarText")
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_3.setFixedSize(self.adaptive_px(44, 38), self.adaptive_px(32, 30))
        self.spinBox.setFixedSize(self.adaptive_px(54, 50), self.adaptive_px(32, 30))
        zoom_bar.addWidget(self.label_3)
        zoom_bar.addWidget(self.spinBox)
        zoom_bar.addSpacing(self.adaptive_px(8, 4))
        zoom_bar.addWidget(make_toolbar_separator())
        zoom_bar.addSpacing(self.adaptive_px(8, 4))
        self.view_angle_text = QtWidgets.QLabel("3D\u89c6\u56fe")
        self.view_angle_text.setObjectName("ToolbarText")
        self.view_angle_text.setAlignment(Qt.AlignCenter)
        self.view_angle_slider = QtWidgets.QSlider(Qt.Horizontal)
        self.view_angle_slider.setRange(15, 75)
        self.view_angle_slider.setValue(self.view_angle_deg)
        self.view_angle_slider.setFixedWidth(self.adaptive_px(180, 120))
        self.view_angle_slider.valueChanged.connect(self.on_view_angle_changed)
        self.view_angle_label = QtWidgets.QLabel("%d deg" % self.view_angle_deg)
        self.view_angle_label.setObjectName("ZoomLabel")
        self.view_angle_label.setAlignment(Qt.AlignCenter)
        self.view_angle_label.setMinimumWidth(self.adaptive_px(74, 64))
        self.view_angle_reset_button = QtWidgets.QPushButton("\u89c6\u89d2\u91cd\u7f6e")
        self.view_angle_reset_button.setObjectName("ZoomButton")
        self.view_angle_reset_button.setFixedSize(self.adaptive_px(116, 108), self.adaptive_px(32, 30))
        self.view_angle_reset_button.clicked.connect(self.reset_view_angle)
        zoom_bar.addWidget(self.view_angle_text)
        zoom_bar.addSpacing(self.adaptive_px(4, 2))
        zoom_bar.addWidget(self.view_angle_slider)
        zoom_bar.addWidget(self.view_angle_label)
        zoom_bar.addWidget(self.view_angle_reset_button)
        locate_layout.addLayout(zoom_bar)
        locate_layout.addWidget(self.graphicsView)

        debug_layout = QtWidgets.QVBoxLayout(self.tab_2)
        debug_layout.setContentsMargins(0, 0, 0, 0)
        debug_layout.setSpacing(self.adaptive_px(8, 6))
        self.debug_splitter = QtWidgets.QSplitter(Qt.Horizontal)
        self.debug_splitter.addWidget(self.edit_log)
        self.debug_parse_panel = QtWidgets.QWidget()
        parse_panel_layout = QtWidgets.QVBoxLayout(self.debug_parse_panel)
        parse_panel_layout.setContentsMargins(0, 0, 0, 0)
        parse_panel_layout.setSpacing(self.adaptive_px(8, 6))
        self.debug_parse_splitter = QtWidgets.QSplitter(Qt.Vertical)

        self.debug_distance_table = QtWidgets.QTableWidget()
        self.debug_distance_table.setColumnCount(6)
        self.debug_distance_table.setHorizontalHeaderLabels(["标签", "帧", "基站", "距离(m)", "RSSI", "状态"])
        self.debug_distance_table.verticalHeader().setVisible(False)
        self.debug_distance_table.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.debug_distance_table.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.debug_distance_table.setAlternatingRowColors(True)
        self.debug_distance_table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.debug_parse_splitter.addWidget(self.debug_distance_table)

        self.debug_plot_panel = QtWidgets.QWidget()
        debug_plot_layout = QtWidgets.QVBoxLayout(self.debug_plot_panel)
        debug_plot_layout.setContentsMargins(0, 0, 0, 0)
        debug_plot_layout.setSpacing(self.adaptive_px(8, 6))
        tag_select_layout = QtWidgets.QHBoxLayout()
        tag_select_layout.addStretch(1)
        tag_select_layout.addWidget(QtWidgets.QLabel("标签:"))
        self.debug_tag_combo = QtWidgets.QComboBox()
        self.debug_tag_combo.setMinimumWidth(self.adaptive_px(140, 120))
        self.debug_tag_combo.currentIndexChanged.connect(self.on_debug_tag_changed)
        tag_select_layout.addWidget(self.debug_tag_combo)
        debug_plot_layout.addLayout(tag_select_layout)
        self.debug_graphics_view = QtWidgets.QGraphicsView()
        self.debug_graphics_view.setRenderHints(QtGui.QPainter.Antialiasing | QtGui.QPainter.TextAntialiasing)
        self.debug_graphics_view.setStyleSheet("background: #F5F8FC; border: 1px solid #AEBBCC; border-radius: 4px;")
        self.debug_graphics_view.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.debug_graphics_view.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.debug_graphics_scene = QtWidgets.QGraphicsScene(self)
        self.debug_graphics_view.setScene(self.debug_graphics_scene)
        debug_plot_layout.addWidget(self.debug_graphics_view, 1)
        self.debug_parse_splitter.addWidget(self.debug_plot_panel)
        self.debug_parse_splitter.setSizes([self.adaptive_px(220, 140), self.adaptive_px(620, 420)])

        parse_panel_layout.addWidget(self.debug_parse_splitter)
        self.debug_parse_panel.setVisible(False)
        self.debug_splitter.addWidget(self.debug_parse_panel)
        self.debug_splitter.setSizes([self.adaptive_px(640, 420), self.adaptive_px(640, 420)])
        debug_layout.addWidget(self.debug_splitter, 1)
        debug_button_layout = QtWidgets.QHBoxLayout()
        debug_button_layout.addStretch(1)
        self.btn_save_log = QtWidgets.QPushButton("\u65e5\u5fd7")
        self.btn_parse = QtWidgets.QPushButton("\u89e3\u6790")
        for debug_button in (self.btn_start, self.btn_clear, self.btn_parse, self.btn_save_log):
            debug_button.setFixedSize(self.adaptive_px(132, 118), self.adaptive_px(43, 38))
        debug_button_layout.addWidget(self.btn_start)
        debug_button_layout.addSpacing(self.adaptive_px(48, 24))
        debug_button_layout.addWidget(self.btn_clear)
        debug_button_layout.addSpacing(self.adaptive_px(48, 24))
        debug_button_layout.addWidget(self.btn_parse)
        debug_button_layout.addSpacing(self.adaptive_px(48, 24))
        debug_button_layout.addWidget(self.btn_save_log)
        debug_button_layout.addStretch(1)
        debug_layout.addLayout(debug_button_layout)

        self.pushButton.setFont(button_font)
        self.lineEdit_Port.setFont(button_font)
        self.label_port_state.setFont(status_font)
        self.com_status_label.setFont(com_font)
        self.label_port_state.setMinimumHeight(self.adaptive_px(34, 30))
        self.com_status_label.setMinimumHeight(self.adaptive_px(34, 30))
        for debug_button in (self.btn_start, self.btn_clear, self.btn_parse, self.btn_save_log):
            debug_button.setFont(button_font)

        self.table_anthor.setRowCount(len(gAnthor_Node_Configure))
        self.table_anthor.setMinimumHeight(self.adaptive_px(154, 138))
        self.table_anthor.setColumnWidth(0, self.adaptive_px(52, 44))
        self.table_anthor.setColumnWidth(1, self.adaptive_px(86, 74))
        self.table_anthor.setColumnWidth(2, self.adaptive_px(62, 52))
        self.table_anthor.setColumnWidth(3, self.adaptive_px(62, 52))
        self.table_anthor.setColumnWidth(4, self.adaptive_px(62, 52))
        self.table_anthor.verticalHeader().setDefaultSectionSize(self.adaptive_px(28, 24))
        self.table_anthor.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.table_anthor.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.table_anthor.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.Fixed)
        self.table_anthor.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.Fixed)
        self.table_anthor.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.Stretch)
        self.table_anthor.horizontalHeader().setSectionResizeMode(3, QtWidgets.QHeaderView.Stretch)
        self.table_anthor.horizontalHeader().setSectionResizeMode(4, QtWidgets.QHeaderView.Stretch)

        self.table_tag.setRowCount(4)
        self.table_tag.setMinimumHeight(self.adaptive_px(154, 138))
        self.table_tag.setColumnWidth(0, self.adaptive_px(83, 70))
        self.table_tag.setColumnWidth(1, self.adaptive_px(70, 57))
        self.table_tag.setColumnWidth(2, self.adaptive_px(70, 57))
        self.table_tag.setColumnWidth(3, self.adaptive_px(70, 57))
        self.table_tag.verticalHeader().setDefaultSectionSize(self.adaptive_px(28, 24))
        self.table_tag.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.table_tag.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.Fixed)
        self.table_tag.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)
        self.table_tag.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.Stretch)
        self.table_tag.horizontalHeader().setSectionResizeMode(3, QtWidgets.QHeaderView.Stretch)

    def center_on_screen(self):
        """Move the window to the current screen center without overflowing."""
        screen = self.screen() or QtGui.QGuiApplication.primaryScreen()
        if screen is None:
            return

        available = screen.availableGeometry()
        frame = self.frameGeometry()
        frame.moveCenter(available.center())
        top_left = frame.topLeft()

        if frame.width() <= available.width():
            top_left.setX(max(available.left(), min(top_left.x(), available.right() - frame.width() + 1)))
        else:
            top_left.setX(available.left())

        if frame.height() <= available.height():
            top_left.setY(max(available.top(), min(top_left.y(), available.bottom() - frame.height() + 1)))
        else:
            top_left.setY(available.top())

        self.move(top_left)

    def apply_business_theme(self):
        """Apply the enterprise industrial data-platform theme."""
        self.setStyleSheet("""
            QMainWindow, QWidget {
                background: #F2F5F9;
                color: #162033;
                font-family: "Microsoft YaHei UI", "Segoe UI", Arial;
            }
            QGroupBox {
                background: #FFFFFF;
                border: 1px solid #C5D1DE;
                border-radius: 6px;
                margin-top: 14px;
                padding-top: 13px;
            }
            QGroupBox::title {
                subcontrol-origin: margin;
                left: 12px;
                padding: 0 7px;
                color: #17324D;
                background: #F2F5F9;
                font-weight: 700;
            }
            QGroupBox#HistoryPanel {
                background: #FFFFFF;
                border: 1px solid #C5D1DE;
                border-radius: 6px;
                margin-top: 0px;
                padding-top: 0px;
            }
            QGroupBox#HistoryPanel::title {
                height: 0px;
                padding: 0px;
                margin: 0px;
            }
            QTabWidget::pane {
                border: 1px solid #C5D1DE;
                background: #FFFFFF;
                top: -1px;
            }
            QTabBar::tab {
                background: #E5ECF3;
                color: #52616F;
                border: 1px solid #C5D1DE;
                border-bottom: none;
                border-top-left-radius: 5px;
                border-top-right-radius: 5px;
                padding: 8px 20px;
                margin-right: 2px;
                font-weight: 700;
            }
            QTabBar::tab:selected {
                background: #FFFFFF;
                color: #12314D;
            }
            QTabBar::tab:disabled {
                background: #EEF3F8;
                color: #8A97A8;
            }
            QTableWidget {
                background: #FFFFFF;
                alternate-background-color: #F5F8FB;
                gridline-color: #D5DFEA;
                border: 1px solid #C5D1DE;
                border-radius: 4px;
                selection-background-color: #2D6F9F;
                selection-color: #FFFFFF;
            }
            QHeaderView::section {
                background: #E4ECF5;
                color: #12314D;
                border: 0;
                border-right: 1px solid #CBD7E3;
                border-bottom: 1px solid #CBD7E3;
                padding: 6px;
                font-weight: 700;
            }
            QLineEdit, QSpinBox, QComboBox, QPlainTextEdit {
                background: #FFFFFF;
                color: #162033;
                border: 1px solid #B7C6D8;
                border-radius: 4px;
                padding: 5px 8px;
                selection-background-color: #2D6F9F;
            }
            QLineEdit:focus, QSpinBox:focus, QComboBox:focus, QPlainTextEdit:focus {
                border: 1px solid #2D74A8;
            }
            QLineEdit:read-only, QSpinBox:disabled, QComboBox:disabled, QLineEdit:disabled {
                background: #E7EDF4;
                color: #667085;
            }
            QPushButton {
                background: #2B5F89;
                color: #FFFFFF;
                border: 1px solid #244F72;
                border-radius: 4px;
                padding: 7px 18px;
                font-weight: 700;
            }
            QPushButton:hover {
                background: #3472A1;
            }
            QPushButton:pressed {
                background: #1D4669;
            }
            QPushButton:disabled {
                background: #D4DDE8;
                color: #6B7280;
                border-color: #C2CCD8;
            }
            QPushButton#ZoomButton {
                background: #FFFFFF;
                color: #17324D;
                border: 1px solid #B7C6D8;
                border-radius: 4px;
                padding: 4px 10px;
            }
            QPushButton#ZoomButton:hover {
                background: #EEF6FC;
                border-color: #6F9AC2;
            }
            QLabel#ZoomLabel {
                background: #FFFFFF;
                color: #17324D;
                border: 1px solid #B7C6D8;
                border-radius: 4px;
                padding: 5px 10px;
                font-weight: 700;
            }
            QLabel#ToolbarText {
                background: transparent;
                color: #17324D;
                border: none;
                padding: 0px 2px;
                font-weight: 700;
            }
            QFrame#ToolbarSeparator {
                background: #C5D1DE;
                color: #C5D1DE;
                border: none;
                max-width: 1px;
            }
            QGraphicsView {
                background: #F8FAFD;
                border: 1px solid #C5D1DE;
                border-radius: 4px;
            }
            QScrollBar:vertical, QScrollBar:horizontal {
                background: #E7EDF4;
                border: none;
                margin: 0;
            }
            QScrollBar::handle:vertical, QScrollBar::handle:horizontal {
                background: #9BACBF;
                border-radius: 3px;
                min-height: 24px;
                min-width: 24px;
            }
            QSplitter::handle {
                background: #D8E1EC;
            }
            QLabel {
                background: transparent;
            }
            QStatusBar {
                background: #16324D;
                color: #FFFFFF;
                border-top: 1px solid #0E253B;
            }
            QStatusBar QLabel {
                color: #FFFFFF;
                padding: 2px 12px;
                font-weight: 600;
            }
        """)
        self.scene.setBackgroundBrush(QBrush(QColor("#F8FAFD")))
        self.edit_log.setStyleSheet(
            'QPlainTextEdit { background: #101826; color: #EAF0F8; '
            'border: 1px solid #314158; border-radius: 4px; '
            'font-family: Consolas, "Microsoft YaHei UI"; font-size: 10pt; }'
        )
        self.debug_graphics_view.setStyleSheet(
            "background: #F8FAFD; border: 1px solid #C5D1DE; border-radius: 4px;"
        )
        self.gQtColor = [
            QColor("#D97706"),
            QColor("#BE123C"),
            QColor("#7C3AED"),
            QColor("#15803D"),
            QColor("#C2410C"),
            QColor("#A21CAF"),
            QColor("#4D7C0F"),
            QColor("#B91C1C"),
            QColor("#92400E"),
            QColor("#6D28D9"),
        ]

    @staticmethod
    def get_local_ip():
        """Pick a useful local IPv4 address without assuming a fixed subnet."""
        candidates = []

        def add_candidate(ip):
            """Append one valid non-loopback IPv4 candidate once."""
            try:
                ip_obj = ipaddress.ip_address(ip)
            except ValueError:
                return
            if ip_obj.version != 4:
                return
            if ip_obj.is_loopback or ip_obj.is_link_local or ip_obj.is_multicast or ip_obj.is_unspecified:
                return
            if ip not in candidates:
                candidates.append(ip)

        for target in ("8.8.8.8", "1.1.1.1", "223.5.5.5", "114.114.114.114"):
            sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            try:
                sock.connect((target, 80))
                add_candidate(sock.getsockname()[0])
            except OSError:
                pass
            finally:
                sock.close()

        try:
            hostname = socket.gethostname()
            for info in socket.getaddrinfo(hostname, None, socket.AF_INET):
                add_candidate(info[4][0])
        except OSError:
            pass

        try:
            hostname = socket.gethostname()
            for ip in socket.gethostbyname_ex(hostname)[2]:
                add_candidate(ip)
        except OSError:
            pass

        for ip in candidates:
            if ipaddress.ip_address(ip).is_private:
                return ip
        if candidates:
            return candidates[0]
        return "127.0.0.1"

    def set_comm_status_style(self, label, state):
        """Style TCP/COM status labels consistently across connection states."""
        colors = {
            "open": "#0F766E",
            "closed": "#B42318",
            "warning": "#B7791F",
        }
        point_size = 12
        label.setStyleSheet(
            "color: %s; font-weight: 700;" %
            colors.get(state, colors["closed"])
        )
        font = label.font()
        font.setPointSize(point_size)
        font.setBold(True)
        label.setFont(font)
        label.setMinimumHeight(34)

    def update_comm_controls(self):
        """Enable or disable TCP/COM controls according to active transport."""
        tcp_open = self.tcp_server.is_open()
        com_open = self.serial_server.is_open()
        tcp_index = self.comm_tab_widget.indexOf(self.tcp_tab)
        com_index = self.comm_tab_widget.indexOf(self.com_tab)

        self.comm_tab_widget.setTabEnabled(tcp_index, not com_open)
        self.comm_tab_widget.setTabEnabled(com_index, not tcp_open)

        self.pushButton.setEnabled(not com_open or tcp_open)
        self.lineEdit_Port.setEnabled((not com_open) and (not tcp_open))

        has_serial_port = bool(self.com_port_combo.currentData())
        self.com_open_button.setEnabled(com_open or ((not tcp_open) and has_serial_port))
        self.com_port_combo.setEnabled((not tcp_open) and (not com_open) and has_serial_port)
        self.com_baud_combo.setEnabled((not tcp_open) and (not com_open))
        self.com_refresh_button.setEnabled((not tcp_open) and (not com_open))

        debug_enabled = tcp_open or com_open
        self.btn_start.setEnabled(debug_enabled)
        self.btn_clear.setEnabled(debug_enabled)
        self.btn_parse.setEnabled(debug_enabled)
        self.btn_save_log.setEnabled(debug_enabled)
        if not debug_enabled and self.enable_log:
            self.enable_log = False
            self.btn_start.setText("\u5f00\u59cb")
        if not debug_enabled and self.file_log_enabled:
            self.stop_file_log()

    def on_serial_status_message(self, message):
        """Reflect asynchronous serial status messages in the COM tab."""
        if self.serial_server.is_open():
            self.set_comm_status_style(self.com_status_label, "open")
        else:
            self.set_comm_status_style(self.com_status_label, "closed")
            if self.com_open_button.text() == "CLOSE":
                self.com_open_button.setText("OPEN")
                self.set_connection_status("未连接")
                self.do_unlock_Table()
        self.com_status_label.setText(message)
        self.update_comm_controls()

    def setup_status_bar(self):
        """Create status-bar fields for connection, algorithm, and display mode."""
        self.connection_status_label = QtWidgets.QLabel("连接状态:未连接")
        self.algorithm_status_label = QtWidgets.QLabel("定位算法:等待数据")
        self.display_status_label = QtWidgets.QLabel("显示模式:2D")
        self.statusBar().setSizeGripEnabled(False)
        self.statusBar().addPermanentWidget(self.connection_status_label, 1)
        self.statusBar().addPermanentWidget(self.algorithm_status_label, 1)
        self.statusBar().addPermanentWidget(self.display_status_label, 1)

    def set_connection_status(self, status):
        """Update connection status text in the status bar."""
        self.connection_status_label.setText("连接状态:%s" % status)

    def set_algorithm_status(self, status):
        """Update algorithm status text in the status bar."""
        self.algorithm_status_label.setText("定位算法:%s" % status)

    def set_display_status(self):
        """Update 2D/3D display-mode text in the status bar."""
        self.display_status_label.setText("显示模式:%s" % self.display_mode)

    def do_lock_Table(self):
        """Lock anchor configuration while TCP or COM is connected."""
        self.table_anthor.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.set_anchor_checkboxes_enabled(False)

    def do_unlock_Table(self):
        """Restore anchor table editing after all transports are closed."""
        self.table_anthor.setEditTriggers(
            QAbstractItemView.DoubleClicked
            | QAbstractItemView.EditKeyPressed
            | QAbstractItemView.AnyKeyPressed
        )
        self.set_anchor_checkboxes_enabled(True)

    def do_adjust_maxhistory(self):
        """Apply the MAX HISTORY spin-box value to tag smoothing history."""
        self.MAX_HISTORY = self.spinBox.value()

    def refresh_serial_ports(self):
        """Refresh COM port candidates from pyserial while preserving selection."""
        current = self.com_port_combo.currentData() or getattr(self, "preferred_com_port", "")
        self.com_port_combo.clear()

        if serial is None or list_ports is None:
            self.com_port_combo.addItem("pyserial not installed", "")
            self.com_status_label.setText("COM: pyserial未安装")
            self.set_comm_status_style(self.com_status_label, "closed")
            self.update_comm_controls()
            return

        ports = list(list_ports.comports())
        for port in ports:
            self.com_port_combo.addItem(port.device, port.device)

        if not ports:
            self.com_port_combo.addItem("\u672a\u53d1\u73b0\u4e32\u53e3", "")
            self.com_status_label.setText("COM: 未发现串口")
            self.set_comm_status_style(self.com_status_label, "warning")
        else:
            index = self.com_port_combo.findData(current)
            if index < 0:
                preferred_keywords = ("USB", "CH340", "CP210", "FTDI", "UART")
                for port in ports:
                    port_text = " ".join([
                        str(getattr(port, "device", "")),
                        str(getattr(port, "description", "")),
                        str(getattr(port, "manufacturer", "")),
                    ]).upper()
                    if "BLUETOOTH" in port_text:
                        continue
                    if any(keyword in port_text for keyword in preferred_keywords):
                        index = self.com_port_combo.findData(port.device)
                        break
            if index < 0:
                index = 0
            if index >= 0:
                self.com_port_combo.setCurrentIndex(index)
                self.preferred_com_port = self.com_port_combo.currentData() or current
            self.com_status_label.setText("COM: 未打开")
            self.set_comm_status_style(self.com_status_label, "closed")

        self.update_comm_controls()

    def do_tcp_server_start(self):
        """Open or close the TCP server from the TCP tab."""
        if self.pushButton.text() == "OPEN":
            if self.serial_server.is_open():
                QMessageBox.information(self, "COM Connected", "Please close COM before opening TCP.")
                self.update_comm_controls()
                return

            try:
                port = int(self.lineEdit_Port.text())
                if not 1 <= port <= 65535:
                    raise ValueError
                self.label_ip.setText(self.get_local_ip())
                self.tcp_server.tcp_init(port)
            except ValueError:
                QMessageBox.warning(self, "Port Error", "Please enter a TCP port from 1 to 65535.")
                return
            except OSError as exc:
                QMessageBox.warning(self, "TCP Open Failed", str(exc))
                return

            self.lineEdit_Port.setReadOnly(True)
            thread = Thread(target=self.tcp_server.accept_client, daemon=True)
            thread.start()
            self.pushButton.setText("CLOSE")
            self.label_port_state.setText("TCP: 已打开")
            self.set_comm_status_style(self.label_port_state, "open")
            self.set_connection_status("TCP \u5df2\u8fde\u63a5 %s:%d" % (self.label_ip.text(), port))

            self.gTag_Result = []
            self.scene.clear()
            self.table_tag.clearContents()
            self.Display_Anthor(gAnthor_Node_Configure)
            self.do_lock_Table()
            self.update_comm_controls()
            return

        reply = QMessageBox.question(self, "Confirm", "Close TCP?", QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
        if reply == QMessageBox.Yes:
            self.lineEdit_Port.setReadOnly(False)
            self.tcp_server.tcp_close()
            self.pushButton.setText("OPEN")
            self.label_port_state.setText("TCP: 未打开")
            self.set_comm_status_style(self.label_port_state, "closed")
            self.set_connection_status("\u672a\u8fde\u63a5")
            self.do_unlock_Table()
            self.update_comm_controls()

    def do_serial_start(self):
        """Open or close the serial reader from the COM tab."""
        if self.com_open_button.text() == "OPEN":
            if self.tcp_server.is_open():
                QMessageBox.information(self, "TCP Connected", "Please close TCP before opening COM.")
                self.update_comm_controls()
                return

            port = self.com_port_combo.currentData()
            if not port:
                QMessageBox.warning(self, "COM Error", "Please select an available serial port.")
                self.update_comm_controls()
                return

            try:
                baudrate = int(self.com_baud_combo.currentText())
                self.serial_server.serial_init(port, baudrate)
            except (ValueError, OSError) as exc:
                QMessageBox.warning(self, "COM Open Failed", str(exc))
                return

            thread = Thread(target=self.serial_server.read_loop, daemon=True)
            thread.start()
            self.com_open_button.setText("CLOSE")
            self.com_status_label.setText("COM: %s 已打开" % port)
            self.set_comm_status_style(self.com_status_label, "open")
            self.set_connection_status("COM \u5df2\u8fde\u63a5 %s @ %d" % (port, baudrate))

            self.gTag_Result = []
            self.scene.clear()
            self.table_tag.clearContents()
            self.Display_Anthor(gAnthor_Node_Configure)
            self.do_lock_Table()
            self.update_comm_controls()
            return

        self.serial_server.serial_close()
        self.com_open_button.setText("OPEN")
        self.com_status_label.setText("COM: 未打开")
        self.set_comm_status_style(self.com_status_label, "closed")
        self.set_connection_status("\u672a\u8fde\u63a5")
        self.do_unlock_Table()
        self.update_comm_controls()
